title:               Bike Touring World
desc: Resources for traveling around the world by bicycle.
tagline:             'The Ultimate Resource for Bicycle Touring'
description:         'Bike Touring World - The Ultimate Resource for Bicycle Touring'
url:                 https://biketouringworld.com/
baseurl:             ''
permalink: '/:title.html'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  
excerpt_separator: "<!-- more -->"
exclude: [jekyll-serve.bat]